server:
  port: 0

spring:
  application:
    name: marketplace-service
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: postgres
    password: moo748
    driverClassName: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone:
        - "http://localhost:8761/eureka"
