version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=game1'
      - 'POSTGRES_PASSWORD=moo748'
      - 'POSTGRES_USER=postgres'
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
#    depends_on:
#      - postgres
    restart: on-failure

  config-server:
    image: config-server:latest
    container_name: config-server
    #    environment:
    #      - 'PAGINATION_MAX_SIZE=50'
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  gateway-server:
    image: gateway-server:latest
    container_name: gateway-server
#    environment:
#      - 'PAGINATION_MAX_SIZE=50'
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
#    depends_on:
#      - user-service
#      - item-service
#      - marketplace-service
    restart: on-failure

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - postgres

  item-service:
    image: item-service:latest
    container_name: item-service
    build:
      context: ./item-service
      dockerfile: Dockerfile
    depends_on:
      - user-service

  marketplace-service:
    image: marketplace-service:latest
    container_name: marketplace-service
    build:
      context: ./marketplace-service
      dockerfile: Dockerfile
    depends_on:
      - item-service
