CREATE TABLE if not exists users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    username VARCHAR(255),
    description VARCHAR(255),
    balance  INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE if not exists roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE if not exists users_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL
);

CREATE TABLE if not exists items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    rarity  VARCHAR(255)                            NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE if not exists marketplace_items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price   INTEGER                                 NOT NULL,
    user_name VARCHAR(255)                          NOT NULL,
    item_name VARCHAR(255)                          NOT NULL,
    item_id BIGINT                                  NOT NULL,
    rarity  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_marketplace_items PRIMARY KEY (id)
);