CREATE TABLE if not exists marketplace_items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price   INTEGER                                 NOT NULL,
    user_name VARCHAR(255)                          NOT NULL,
    item_name VARCHAR(255)                          NOT NULL,
    item_id BIGINT                                  NOT NULL,
    rarity  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_marketplace_items PRIMARY KEY (id)
);