server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
            file:
            - "D:/4/highload/high-perfomance-system-2/config-server/src/main/resources/configs"

eureka:
  client:
    service-url:
      defaultZone:
        - "http://localhost:8761/eureka"
