server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rimnvd/configs.git

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka