server:
  port: 0

spring:
  application:
    name: item-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone:
        - "http://localhost:8761/eureka"
