server:
  port: 0

spring:
  application:
    name: item-service
  config:
    import: optional:configserver:http://config-server:8888
#    import: optional:configserver:http://localhost:8888

resilience4j:
  circuitbreaker:
    instances:
      updateBalance:
        minimum-number-of-calls: 50