name: run tests

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: | # optional
            gateway/pom.xml
            config-server/pom.xml
            eureka-server/pom.xml
            item-service/pom.xml
            marketplace-service/pom.xml
            user-service/pom.xml
      - name: Grant execute permission for maven
        run: chmod +x mvn
      - name: Build with Maven
        run: ./mvn test